# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Gonçalves
tagline:          'Personal site'
description:      'R&D Security Consultant.'
url:              http://danieldiasgoncalves.com
baseurl:          /

author:
  name:           'Daniel Gonçalves'
  email:          mailto:mail@danieldiasgoncalves.com
  url:            http://danieldiasgoncalves.com
  gravatar:       479082164e06d6b1b0a0300095d541cd

paginate:         5

# Custom vars
version:          2.1.0

social:
  github:         https://github.com/2phost
  linkedin:       https://linkedin.com/in/danieldiasg
  email:          mailto:mail@danieldiasgoncalves.com
