# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Daniel Gonçalves

description: My projects
author:
  name: Daniel Gonçalves
  email: 
  github: 2phost
  twitter: 
  pinterest: 
  linkedin: danieldiasg
  bio: I have a M.Sc. in Information Systems and Computer Engineering from Instituto Superior Técnico, University of Lisboa, whose main area is Distributed Systems and complementary area is Software Engineering.

        My interests are in network security, information security, distributed systems, kernel development and machine learning.

  email_md5: 479082164e06d6b1b0a0300095d541cd

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
publications_path: publications.html

BASE_PATH:
